# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="bira-custom"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  pyenv
  zsh-autosuggestions
  zsh-completions
)

source $ZSH/oh-my-zsh.sh
source $HOME/.aliases
if [ -f "$HOME/.local_profile" ]; then
    source $HOME/.local_profile
fi

export KEYTIMEOUT=1

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# added by travis gem
[ -f /Users/aykhaiweng/.travis/travis.sh ] && source /Users/aykhaiweng/.travis/travis.sh

# fix for Ctrl E not working
bindkey -e

# Added by Krypton
export GPG_TTY=$(tty)

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH="/usr/local/opt/ruby/bin:$PATH"
